/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.Alimento;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JFrame;
/**
 *
 * @author alumnogreibd
 */
public class VAlimentos extends javax.swing.JDialog {
    aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VALimentos
     */
    
    public VAlimentos(java.awt.Frame parent, boolean modal,aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        setTitle("Gestión Alimentos");
        obterAlimentos();
        listenerSeleccionAlimentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_alimentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreAlimento = new javax.swing.JTextField();
        tf_tipoAlimento = new javax.swing.JTextField();
        btn_anadirAlimento = new javax.swing.JButton();
        btn_borrarAlimento = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_asignarAlimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla_alimentos.setModel(new ModeloTablaAlimentos());
        jScrollPane1.setViewportView(tabla_alimentos);

        jLabel1.setText("Alimentos");

        jLabel2.setText("Nombre");

        jLabel3.setText("Tipo ");

        tf_nombreAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreAlimentoActionPerformed(evt);
            }
        });

        btn_anadirAlimento.setText("Añadir");
        btn_anadirAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirAlimentoActionPerformed(evt);
            }
        });

        btn_borrarAlimento.setText("Borrar");
        btn_borrarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarAlimentoActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_asignarAlimento.setText("Asignar alimento");
        btn_asignarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignarAlimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_asignarAlimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_anadirAlimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                        .addComponent(btn_borrarAlimento))
                                    .addComponent(tf_tipoAlimento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nombreAlimento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn_salir)))
                                .addGap(15, 15, 15))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombreAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tipoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_anadirAlimento)
                            .addComponent(btn_borrarAlimento))
                        .addGap(18, 18, 18)
                        .addComponent(btn_asignarAlimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreAlimentoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_anadirAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirAlimentoActionPerformed
        
        if (!tf_nombreAlimento.getText().isEmpty() && !tf_tipoAlimento.getText().isEmpty()) {
            ModeloTablaAlimentos mta =(ModeloTablaAlimentos) tabla_alimentos.getModel();
        
            List<Alimento> alAux = mta.getFilas();
            
            for (Alimento a : alAux) {
                if (a.getNombre().equals(tf_nombreAlimento.getText()) && a.getTipo().equals(tf_tipoAlimento.getText())) {
                   
                    return;
                }
            }
            if (fa.anadirAlimento(tf_nombreAlimento.getText(), tf_tipoAlimento.getText()) != -1) {
                obterAlimentos();
            }
            
        }
        
    }//GEN-LAST:event_btn_anadirAlimentoActionPerformed

    private void btn_borrarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarAlimentoActionPerformed
        if (!tf_nombreAlimento.getText().isEmpty() && !tf_tipoAlimento.getText().isEmpty()) {
            
            if (fa.borrarAlimento(tf_nombreAlimento.getText(), tf_tipoAlimento.getText()) != -1) {
                obterAlimentos();
                tf_nombreAlimento.setText("");
                tf_tipoAlimento.setText("");
            }
        
        }
    }//GEN-LAST:event_btn_borrarAlimentoActionPerformed

    private void btn_asignarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignarAlimentoActionPerformed
    ModeloTablaAlimentos mta;
        
    mta =(ModeloTablaAlimentos) tabla_alimentos.getModel();
       
    VConsumirAlimentos vca = new VConsumirAlimentos( (JFrame) getParent(), true, fa, mta.getFila(tabla_alimentos.getSelectedRow()));
    vca.setVisible(true);
   
    }//GEN-LAST:event_btn_asignarAlimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anadirAlimento;
    private javax.swing.JButton btn_asignarAlimento;
    private javax.swing.JButton btn_borrarAlimento;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_alimentos;
    private javax.swing.JTextField tf_nombreAlimento;
    private javax.swing.JTextField tf_tipoAlimento;
    // End of variables declaration//GEN-END:variables

    private void obterAlimentos() {
        ModeloTablaAlimentos mta;
        
        mta =(ModeloTablaAlimentos) tabla_alimentos.getModel();
        mta.setFilas(fa.obtenerAlimentos());
    }
    
     private void listenerSeleccionAlimentos() {
        tabla_alimentos.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
                int fila = tabla_alimentos.getSelectedRow();
                if (fila != -1) {
                    String nomeAlimento = tabla_alimentos.getValueAt(fila, 0).toString();
                    String tipoAlimento = tabla_alimentos.getValueAt(fila, 1).toString();
                    tf_nombreAlimento.setText(nomeAlimento);
                    tf_tipoAlimento.setText(tipoAlimento);
                }
            }

            @Override
            public void mousePressed(MouseEvent me) {
               
            }

            @Override
            public void mouseReleased(MouseEvent me) {
               
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                
            }

            @Override
            public void mouseExited(MouseEvent me) {
               
            }

   
        }
        );
    }
    
    
}
