/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.*;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jaime
 */
public class VAreasGeograficas extends javax.swing.JDialog {
    
    FachadaAplicacion fa;
    private VPrincipal padre;
    private Area selectedArea;

    /**
     * Creates new form VAreasGeograficas
     */
    public VAreasGeograficas(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        padre = (VPrincipal) parent;
        Editarbtn.setEnabled(false);
        Bprrarbtn.setEnabled(false);
        
        configurarTablaAreas();

    }
    
    private void configurarTablaAreas() {
    TableColumnModel columnModel = tablaAreas.getColumnModel();
    columnModel.getColumn(0).setPreferredWidth(300); 

    tablaAreas.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int selectedRow = tablaAreas.getSelectedRow();
            if (selectedRow >= 0) {
                ModeloTablaAreas modelo = (ModeloTablaAreas) tablaAreas.getModel();
                selectedArea = modelo.getFila(selectedRow);
                Editarbtn.setEnabled(true);
                Bprrarbtn.setEnabled(true);
            } else {
                selectedArea = null;
                Editarbtn.setEnabled(false);
                Bprrarbtn.setEnabled(false);
            }
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarTF = new javax.swing.JTextField();
        Buscarbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAreas = new javax.swing.JTable();
        Nuevobtn = new javax.swing.JButton();
        Editarbtn = new javax.swing.JButton();
        Bprrarbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buscarTF.setToolTipText("Nombre del área  geográfica");
        buscarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTFActionPerformed(evt);
            }
        });

        Buscarbtn.setText("Buscar");
        Buscarbtn.setToolTipText("Buscar área geográfica");
        Buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarbtnActionPerformed(evt);
            }
        });

        tablaAreas.setModel(new ModeloTablaAreas());
        tablaAreas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaAreas);

        Nuevobtn.setText("Nuevo");
        Nuevobtn.setToolTipText("Crear nueva área geográfica");
        Nuevobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevobtnActionPerformed(evt);
            }
        });

        Editarbtn.setText("Editar");
        Editarbtn.setToolTipText("Editar el área seleccionada");
        Editarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarbtnActionPerformed(evt);
            }
        });

        Bprrarbtn.setText("Borrar");
        Bprrarbtn.setToolTipText("Eliminar el área seleccionada");
        Bprrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BprrarbtnActionPerformed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(231, 76, 60));
        exitbtn.setText("Salir");
        exitbtn.setToolTipText("Cerrar esta ventana");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Buscarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nuevobtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Editarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bprrarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitbtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscarbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Nuevobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bprrarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTFActionPerformed
        buscarAreas();
    }//GEN-LAST:event_buscarTFActionPerformed

    private void BuscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarbtnActionPerformed
        buscarAreas();
    }//GEN-LAST:event_BuscarbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void BprrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BprrarbtnActionPerformed
        borrarArea();
        buscarAreas();
        Editarbtn.setEnabled(false);
        Bprrarbtn.setEnabled(false);
        if (tablaAreas.getRowCount() != 0) {
            tablaAreas.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_BprrarbtnActionPerformed

    private void EditarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarbtnActionPerformed
        new VAreasEditar(this.padre, true, fa, selectedArea).setVisible(true);
        buscarAreas();  
    }//GEN-LAST:event_EditarbtnActionPerformed

    private void NuevobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevobtnActionPerformed
        new VAreasNuevo(this.padre, true, fa).setVisible(true);
        buscarAreas();
    }//GEN-LAST:event_NuevobtnActionPerformed

    private void buscarAreas() {
        String textoBusqueda = buscarTF.getText();
        List<Area> areas = fa.buscarAreas(textoBusqueda);

        ModeloTablaAreas modeloTabla = (ModeloTablaAreas) tablaAreas.getModel();
        modeloTabla.setFilas((ArrayList<Area>) areas);

        boolean hayResultados = !areas.isEmpty();
        Editarbtn.setEnabled(hayResultados);
        Bprrarbtn.setEnabled(hayResultados);

        if (hayResultados) {
            tablaAreas.setRowSelectionInterval(0, 0);
        }
    }

    private void borrarArea() {
     fa.eliminarArea(selectedArea.getNombreReserva());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bprrarbtn;
    private javax.swing.JButton Buscarbtn;
    private javax.swing.JButton Editarbtn;
    private javax.swing.JButton Nuevobtn;
    private javax.swing.JTextField buscarTF;
    private javax.swing.JButton exitbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAreas;
    // End of variables declaration//GEN-END:variables
}
