/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.*;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jaime
 */
public class VAreasGeograficas extends javax.swing.JDialog {
    
    FachadaAplicacion fa;
    private VPrincipal padre;
    private Area selectedArea;

    /**
     * Creates new form VAreasGeograficas
     */
    public VAreasGeograficas(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        padre = (VPrincipal) parent;
        bEditar.setEnabled(false);
        bBorrar.setEnabled(false);
        
        TableColumnModel columnModel = tablaAreas.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(300); 

        tablaAreas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {  // This ensures we only handle the final event
                int selectedRow = tablaAreas.getSelectedRow();
                if (selectedRow >= 0) {
                    ModeloTablaAreas modelo = (ModeloTablaAreas) tablaAreas.getModel();
                    selectedArea = modelo.getFila(selectedRow);
                    bEditar.setEnabled(true);
                    bBorrar.setEnabled(true);
                } else {
                    selectedArea = null;
                    bEditar.setEnabled(false);
                    bBorrar.setEnabled(false);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoBuscar = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAreas = new javax.swing.JTable();
        bNuevo = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textoBuscar.setToolTipText("Nombre del área  geográfica");
        textoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBuscarActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.setToolTipText("Buscar área geográfica");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        tablaAreas.setModel(new ModeloTablaAreas());
        tablaAreas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaAreas);

        bNuevo.setText("Nuevo");
        bNuevo.setToolTipText("Crear nueva área geográfica");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.setToolTipText("Editar el área seleccionada");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.setToolTipText("Eliminar el área seleccionada");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.setToolTipText("Cerrar esta ventana");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNuevo)
                    .addComponent(bEditar)
                    .addComponent(bBorrar)
                    .addComponent(bSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBuscarActionPerformed
        buscarAreas();
    }//GEN-LAST:event_textoBuscarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        buscarAreas();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        borrarArea();
        buscarAreas();
        bEditar.setEnabled(false);
        bBorrar.setEnabled(false);
        if (tablaAreas.getRowCount() != 0) {
            tablaAreas.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        new VAreasEditar(this.padre, true, fa, selectedArea).setVisible(true);
        buscarAreas();  
    }//GEN-LAST:event_bEditarActionPerformed

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        new VAreasNuevo(this.padre, true, fa).setVisible(true);
        buscarAreas();
    }//GEN-LAST:event_bNuevoActionPerformed

    private void buscarAreas() {
        String textoBusqueda = textoBuscar.getText();
        ArrayList<Area> areas = (ArrayList<Area>) fa.buscarAreas(textoBusqueda);
        ModeloTablaAreas modeloTablaAreas = (ModeloTablaAreas) tablaAreas.getModel();
        modeloTablaAreas.setFilas(areas);

        if (modeloTablaAreas.getRowCount() > 0) {
            tablaAreas.setRowSelectionInterval(0, 0);
            bEditar.setEnabled(true);
            bBorrar.setEnabled(true);
        } else {
            bEditar.setEnabled(false);
            bBorrar.setEnabled(false);
        }
    }

    private void borrarArea() {
     fa.eliminarArea(selectedArea.getNombreReserva());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAreas;
    private javax.swing.JTextField textoBuscar;
    // End of variables declaration//GEN-END:variables
}
