/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.ClinicaMedica;
import aplicacion.Ejemplar;
import java.awt.Frame;

/**
 *
 * @author alumnogreibd
 */

 
public class VClinicas extends javax.swing.JDialog {
     aplicacion.FachadaAplicacion fa;
     Ejemplar ejemplarRevisado;
    /**
     * Creates new form VClinicas
     */
    public VClinicas(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Ejemplar ejemplar) {
        super(parent, modal);
        this.ejemplarRevisado = ejemplar;
        initComponents();
        this.fa=fa;
        TablaClinicas.setModel(new ModeloTablaClinicasMedicas());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaClinicas = new javax.swing.JTable();
        nombreField = new javax.swing.JTextField();
        ubicacionField = new javax.swing.JTextField();
        numField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AñadirClinicaBoton = new javax.swing.JButton();
        BorrarBoton = new javax.swing.JButton();
        AñadirRevisionBoton = new javax.swing.JButton();
        BuscarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaClinicas.setModel(new ModeloTablaClinicasMedicas());
        jScrollPane2.setViewportView(TablaClinicas);

        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("ubicación");

        jLabel3.setText("Nº Trabajadores");

        AñadirClinicaBoton.setText("Añadir Clinica");
        AñadirClinicaBoton.setActionCommand(" Añadir Clinica");
        AñadirClinicaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirClinicaBotonActionPerformed(evt);
            }
        });

        BorrarBoton.setText("Borrar");
        BorrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarBotonActionPerformed(evt);
            }
        });

        AñadirRevisionBoton.setText("Añadir Revision");
        AñadirRevisionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirRevisionBotonActionPerformed(evt);
            }
        });

        BuscarBoton.setText("Buscar");
        BuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ubicacionField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BorrarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AñadirClinicaBoton)
                        .addGap(18, 18, 18)
                        .addComponent(AñadirRevisionBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(BuscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubicacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BuscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrarBoton)
                    .addComponent(AñadirClinicaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AñadirRevisionBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void AñadirClinicaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirClinicaBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirClinicaBotonActionPerformed

    private void BorrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarBotonActionPerformed

    private void AñadirRevisionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirRevisionBotonActionPerformed
            ModeloTablaClinicasMedicas modelo = (ModeloTablaClinicasMedicas) TablaClinicas.getModel();
            int seleccionada = TablaClinicas.getSelectedRow();
            if(seleccionada != -1){
                //falta transaccion de añadir xd pero esta es la idea
                ClinicaMedica clinicaSeleccionada = modelo.getFila(seleccionada);
                fa.crearRevision(clinicaSeleccionada,this.ejemplarRevisado);
                
            }
            
    }//GEN-LAST:event_AñadirRevisionBotonActionPerformed
private void buscarUsuarios(){
    ModeloTablaClinicasMedicas mt;
    mt=(ModeloTablaClinicasMedicas) TablaClinicas.getModel();
 
    String textoBusqueda= nombreField.getText().trim();
   
    mt.setFilas(fa.obtenerClinicas(textoBusqueda));
        
    }
    private void BuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBotonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirClinicaBoton;
    private javax.swing.JButton AñadirRevisionBoton;
    private javax.swing.JButton BorrarBoton;
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JTable TablaClinicas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField numField;
    javax.swing.JTextField ubicacionField;
    // End of variables declaration//GEN-END:variables
/*
private void buscarUsuarios(){
    ModeloTablaTrabajadores mt;
    mt=(ModeloTablaTrabajadores) TablaTrabajadores.getModel();
 
    String textoBusqueda=TextFileBuscarTrabajadores.getText().trim();
    nombreCheck.setVisible(true);
    dniCheck.setVisible(true);
    if (textoBusqueda.isEmpty()) {
        
     mt.setFilas(fa.obtenerTodosLosTrabajadores());
    }
    else if (dniCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresDni(textoBusqueda));
        nombreCheck.setVisible(false);
        
    }else if (nombreCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresNombre(textoBusqueda));
        dniCheck.setVisible(false);
        
    }else{
        VAviso va= new VAviso((Frame)getParent(), true, "Selecciona un criterio de búsqueda");
        va.setVisible(true);
        
    }
  */



}
