/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.ClinicaMedica;
import aplicacion.Ejemplar;
import aplicacion.Revision;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author alumnogreibd
 */

 
public class VClinicas extends javax.swing.JDialog {
     aplicacion.FachadaAplicacion fa;
     Ejemplar ejemplarRevisado;
    /**
     * Creates new form VClinicas
     */
    public VClinicas(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Ejemplar ejemplar) {
        super(parent, modal);
        this.ejemplarRevisado = ejemplar;
        initComponents();
        this.fa=fa;
        TablaClinicas.setModel(new ModeloTablaClinicasMedicas());
        Integer id = ejemplarRevisado.getId();
        EjemplarField.setText(id.toString());
        listenerSeleccionClinica();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaClinicas = new javax.swing.JTable();
        nombreField = new javax.swing.JTextField();
        ubicacionField = new javax.swing.JTextField();
        numField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AñadirClinicaBoton = new javax.swing.JButton();
        BorrarBoton = new javax.swing.JButton();
        AñadirRevisionBoton = new javax.swing.JButton();
        BuscarBoton = new javax.swing.JButton();
        EjemplarField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SalirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaClinicas.setModel(new ModeloTablaClinicasMedicas());
        jScrollPane2.setViewportView(TablaClinicas);

        nombreField.setPreferredSize(new java.awt.Dimension(100, 30));
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        ubicacionField.setPreferredSize(new java.awt.Dimension(100, 30));

        numField.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel1.setText("Nombre");

        jLabel2.setText("ubicación");

        jLabel3.setText("Nº Trabajadores");

        AñadirClinicaBoton.setText("Añadir Clinica");
        AñadirClinicaBoton.setActionCommand(" Añadir Clinica");
        AñadirClinicaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirClinicaBotonActionPerformed(evt);
            }
        });

        BorrarBoton.setText("Borrar");
        BorrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarBotonActionPerformed(evt);
            }
        });

        AñadirRevisionBoton.setText("Añadir Revision");
        AñadirRevisionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirRevisionBotonActionPerformed(evt);
            }
        });

        BuscarBoton.setText("Buscar");
        BuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBotonActionPerformed(evt);
            }
        });

        EjemplarField.setEditable(false);
        EjemplarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjemplarFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("ejemplar para revisión ->");

        SalirBoton.setText("salir");
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(AñadirClinicaBoton)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalirBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BorrarBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(ubicacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EjemplarField)
                        .addGap(18, 18, 18)
                        .addComponent(AñadirRevisionBoton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubicacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñadirClinicaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BorrarBoton)
                    .addComponent(SalirBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AñadirRevisionBoton)
                    .addComponent(EjemplarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void AñadirClinicaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirClinicaBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirClinicaBotonActionPerformed

    private void BorrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarBotonActionPerformed

    private void AñadirRevisionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirRevisionBotonActionPerformed
            ModeloTablaClinicasMedicas modelo = (ModeloTablaClinicasMedicas) TablaClinicas.getModel();
            int seleccionada = TablaClinicas.getSelectedRow();
            if(seleccionada != -1){
                //falta transaccion de añadir xd pero esta es la idea
                ClinicaMedica clinicaSeleccionada = modelo.getFila(seleccionada);
                fa.crearRevision(clinicaSeleccionada,this.ejemplarRevisado);
                
            }
            
    }//GEN-LAST:event_AñadirRevisionBotonActionPerformed
private void buscarClinicas(){
    ModeloTablaClinicasMedicas mt;
    mt=(ModeloTablaClinicasMedicas) TablaClinicas.getModel();
 
    String textoBusqueda= nombreField.getText().trim();
   
    mt.setFilas(fa.obtenerClinicas(textoBusqueda));
        
    }
    private void BuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBotonActionPerformed
        buscarClinicas();
    }//GEN-LAST:event_BuscarBotonActionPerformed

    private void EjemplarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjemplarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EjemplarFieldActionPerformed

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirBotonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirClinicaBoton;
    private javax.swing.JButton AñadirRevisionBoton;
    private javax.swing.JButton BorrarBoton;
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JTextField EjemplarField;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JTable TablaClinicas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField numField;
    javax.swing.JTextField ubicacionField;
    // End of variables declaration//GEN-END:variables
/*
private void buscarUsuarios(){
    ModeloTablaTrabajadores mt;
    mt=(ModeloTablaTrabajadores) TablaTrabajadores.getModel();
 
    String textoBusqueda=TextFileBuscarTrabajadores.getText().trim();
    nombreCheck.setVisible(true);
    dniCheck.setVisible(true);
    if (textoBusqueda.isEmpty()) {
        
     mt.setFilas(fa.obtenerTodosLosTrabajadores());
    }
    else if (dniCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresDni(textoBusqueda));
        nombreCheck.setVisible(false);
        
    }else if (nombreCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresNombre(textoBusqueda));
        dniCheck.setVisible(false);
        
    }else{
        VAviso va= new VAviso((Frame)getParent(), true, "Selecciona un criterio de búsqueda");
        va.setVisible(true);
        
    }
  */
        private void listenerSeleccionClinica() {
        TablaClinicas.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
                int fila = TablaClinicas.getSelectedRow();
                if (fila != -1) {
                    ModeloTablaClinicasMedicas mt;
                    mt=(ModeloTablaClinicasMedicas)TablaClinicas.getModel();
                    ClinicaMedica clini = mt.getFila(fila);
                    nombreField.setText(clini.getNombre());
                    ubicacionField.setText(clini.getUbicacion());
                    Integer numero;
                    numero = clini.getNumEmpleados();
                    numField.setText(numero.toString());
                    
                    
                    
                    
                   
                }
                          
                
            }

            @Override
            public void mousePressed(MouseEvent me) {
               
            }

            @Override
            public void mouseReleased(MouseEvent me) {
               
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                
            }

            @Override
            public void mouseExited(MouseEvent me) {
               
            }

   
        }
        );
    }



}
