/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.ClinicaMedica;
import aplicacion.Ejemplar;
import aplicacion.Revision;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author alumnogreibd
 */

 
public class VClinicas extends javax.swing.JDialog {
     aplicacion.FachadaAplicacion fa;
     Ejemplar ejemplarRevisado;
    /**
     * Creates new form VClinicas
     */
    public VClinicas(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Ejemplar ejemplar) {
        super(parent, modal);
        this.ejemplarRevisado = ejemplar;
        initComponents();
        this.fa=fa;
        TablaClinicas.setModel(new ModeloTablaClinicasMedicas());
        Integer id = ejemplarRevisado.getId();
        tf_ejemplarRevision.setText(id.toString());
        listenerSeleccionClinica();
        BorrarBoton.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaClinicas = new javax.swing.JTable();
        tf_nomeRevision = new javax.swing.JTextField();
        tf_ubicacion = new javax.swing.JTextField();
        tf_numTraballadores = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_engadirClinica = new javax.swing.JButton();
        BorrarBoton = new javax.swing.JButton();
        btn_engadirRevision = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        tf_ejemplarRevision = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaClinicas.setModel(new ModeloTablaClinicasMedicas());
        jScrollPane2.setViewportView(TablaClinicas);

        tf_nomeRevision.setPreferredSize(new java.awt.Dimension(100, 30));
        tf_nomeRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeRevisionActionPerformed(evt);
            }
        });

        tf_ubicacion.setPreferredSize(new java.awt.Dimension(100, 30));

        tf_numTraballadores.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel1.setText("Nombre");

        jLabel2.setText("Ubicación");

        jLabel3.setText("Nº Trabajadores");

        btn_engadirClinica.setText("Añadir Clinica");
        btn_engadirClinica.setActionCommand(" Añadir Clinica");
        btn_engadirClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_engadirClinicaActionPerformed(evt);
            }
        });

        BorrarBoton.setText("Borrar");
        BorrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarBotonActionPerformed(evt);
            }
        });

        btn_engadirRevision.setText("Añadir Revision");
        btn_engadirRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_engadirRevisionActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tf_ejemplarRevision.setEditable(false);
        tf_ejemplarRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ejemplarRevisionActionPerformed(evt);
            }
        });

        jLabel4.setText("Ejemplar para revisión ->");

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_ejemplarRevision)
                        .addGap(151, 151, 151))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_engadirRevision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_engadirClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BorrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nomeRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(tf_numTraballadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tf_nomeRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(tf_numTraballadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_engadirClinica)
                    .addComponent(BorrarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_ejemplarRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_engadirRevision)
                    .addComponent(btn_salir)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nomeRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeRevisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeRevisionActionPerformed

    private void btn_engadirClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_engadirClinicaActionPerformed
          if (!tf_nomeRevision.getText().isEmpty() && !tf_ubicacion.getText().isEmpty()
                 &&!tf_numTraballadores.getText().isEmpty()) {
            String numS = tf_numTraballadores.getText();
            Integer num = Integer.parseInt(numS);
            ClinicaMedica clinica = new ClinicaMedica(tf_nomeRevision.getText(),tf_ubicacion.getText(),num);
            fa.nuevaClinica(clinica);
            ModeloTablaClinicasMedicas mt;
            mt=(ModeloTablaClinicasMedicas) TablaClinicas.getModel();


            mt.setFilas(fa.obtenerClinicas(""));
         
            
        }
        
            
    }//GEN-LAST:event_btn_engadirClinicaActionPerformed

    private void BorrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarBotonActionPerformed
            ModeloTablaClinicasMedicas modelo = (ModeloTablaClinicasMedicas) TablaClinicas.getModel();
            int seleccionada = TablaClinicas.getSelectedRow();
            if(seleccionada != -1){
                //falta transaccion de añadir xd pero esta es la idea
                ClinicaMedica clinicaSeleccionada = modelo.getFila(seleccionada);
                fa.borrarClinica(clinicaSeleccionada);
                tf_numTraballadores.setText("");
                tf_nomeRevision.setText("");
                tf_ubicacion.setText("");
                ModeloTablaClinicasMedicas mt;
                mt=(ModeloTablaClinicasMedicas) TablaClinicas.getModel();

                String textoBusqueda= tf_nomeRevision.getText().trim();

                mt.setFilas(fa.obtenerClinicas(textoBusqueda));
                
            }
    }//GEN-LAST:event_BorrarBotonActionPerformed

    private void btn_engadirRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_engadirRevisionActionPerformed
            ModeloTablaClinicasMedicas modelo = (ModeloTablaClinicasMedicas) TablaClinicas.getModel();
            int seleccionada = TablaClinicas.getSelectedRow();
            if(seleccionada != -1){
                //falta transaccion de añadir xd pero esta es la idea
                ClinicaMedica clinicaSeleccionada = modelo.getFila(seleccionada);
                fa.crearRevision(clinicaSeleccionada,this.ejemplarRevisado);
               
                
            }
            
    }//GEN-LAST:event_btn_engadirRevisionActionPerformed
private void buscarClinicas(){
    ModeloTablaClinicasMedicas mt;
    mt=(ModeloTablaClinicasMedicas) TablaClinicas.getModel();
 
    String textoBusqueda= tf_nomeRevision.getText().trim();
   
    mt.setFilas(fa.obtenerClinicas(textoBusqueda));
        
    }
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        buscarClinicas();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tf_ejemplarRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ejemplarRevisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ejemplarRevisionActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarBoton;
    private javax.swing.JTable TablaClinicas;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_engadirClinica;
    private javax.swing.JButton btn_engadirRevision;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tf_ejemplarRevision;
    private javax.swing.JTextField tf_nomeRevision;
    private javax.swing.JTextField tf_numTraballadores;
    javax.swing.JTextField tf_ubicacion;
    // End of variables declaration//GEN-END:variables
/*
private void buscarUsuarios(){
    ModeloTablaTrabajadores mt;
    mt=(ModeloTablaTrabajadores) TablaTrabajadores.getModel();
 
    String textoBusqueda=TextFileBuscarTrabajadores.getText().trim();
    nombreCheck.setVisible(true);
    dniCheck.setVisible(true);
    if (textoBusqueda.isEmpty()) {
        
     mt.setFilas(fa.obtenerTodosLosTrabajadores());
    }
    else if (dniCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresDni(textoBusqueda));
        nombreCheck.setVisible(false);
        
    }else if (nombreCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresNombre(textoBusqueda));
        dniCheck.setVisible(false);
        
    }else{
        VAviso va= new VAviso((Frame)getParent(), true, "Selecciona un criterio de búsqueda");
        va.setVisible(true);
        
    }
  */
        private void listenerSeleccionClinica() {
        TablaClinicas.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
                int fila = TablaClinicas.getSelectedRow();
                if (fila != -1) {
                    BorrarBoton.setEnabled(true);
                    ModeloTablaClinicasMedicas mt;
                    mt=(ModeloTablaClinicasMedicas)TablaClinicas.getModel();
                    ClinicaMedica clini = mt.getFila(fila);
                    tf_nomeRevision.setText(clini.getNombre());
                    tf_ubicacion.setText(clini.getUbicacion());
                    Integer numero;
                    numero = clini.getNumEmpleados();
                    tf_numTraballadores.setText(numero.toString());
                    
                    
                    
                    
                   
                }else{
                    BorrarBoton.setEnabled(false);
                    
                }
                          
                
            }

            @Override
            public void mousePressed(MouseEvent me) {
               
            }

            @Override
            public void mouseReleased(MouseEvent me) {
               
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                
            }

            @Override
            public void mouseExited(MouseEvent me) {
               
            }

   
        }
        );
    }



}
