/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Alimento;
import aplicacion.ConsumirAlimento;
import aplicacion.Ejemplar;
import aplicacion.Especie;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;

/**
 *
 * @author alumnogreibd
 */
public class VConsumirAlimentos extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VALimentos
     */
    Alimento alimento;

    public VConsumirAlimentos(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Alimento alimento) {
        super(parent, modal);
        this.fa = fa;
        this.alimento = alimento;
        initComponents();
        setTitle("Gestión Consumir-Alimentos");
        tf_idAlimento.setText(String.valueOf(alimento.getId()));
        
        obterEjemplares();
        obterConsumirAlimentos(alimento.getId());
        listenerEjemplares();
        listenerConsumirAlimentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_ejemplares = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_anadirConsAlimento = new javax.swing.JButton();
        btn_borrarConsAlimento = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_consAlimentos = new javax.swing.JTable();
        tf_idEjemplar = new javax.swing.JTextField();
        tf_nomCientificoEjemplar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_cantidad = new javax.swing.JTextField();
        tf_frecuencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_idAlimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla_ejemplares.setModel(new ModeloTablaEjemplares());
        jScrollPane1.setViewportView(tabla_ejemplares);

        jLabel1.setText("Ejemplares");

        btn_anadirConsAlimento.setText("Añadir");
        btn_anadirConsAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirConsAlimentoActionPerformed(evt);
            }
        });

        btn_borrarConsAlimento.setText("Borrar");
        btn_borrarConsAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarConsAlimentoActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        jLabel4.setText("Consumir Alimentos");

        tabla_consAlimentos.setModel(new ModeloTablaConsumirAlimentos()
        );
        jScrollPane2.setViewportView(tabla_consAlimentos);

        tf_idEjemplar.setEnabled(false);

        tf_nomCientificoEjemplar.setEnabled(false);

        jLabel2.setText("ID");

        jLabel3.setText("Nombre científico");

        tf_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cantidadActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad");

        jLabel6.setText("Frecuencia");

        jLabel7.setText("ID Alimento");

        tf_idAlimento.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_anadirConsAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_borrarConsAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tf_idAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tf_frecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_idEjemplar, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nomCientificoEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_salir)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_idEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomCientificoEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_idAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_frecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_anadirConsAlimento)
                    .addComponent(btn_borrarConsAlimento))
                .addGap(35, 35, 35)
                .addComponent(btn_salir)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_borrarConsAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarConsAlimentoActionPerformed

        
        if (fa.borrarConsumirAlimento(Integer.parseInt(tf_idEjemplar.getText()), tf_nomCientificoEjemplar.getText(), Integer.parseInt(tf_idAlimento.getText())) != -1) {
            obterConsumirAlimentos( Integer.parseInt(tf_idEjemplar.getText()));
            
            tf_idEjemplar.setText("");
            tf_nomCientificoEjemplar.setText("");
            tf_cantidad.setText("");
            tf_frecuencia.setText("");
        }


    }//GEN-LAST:event_btn_borrarConsAlimentoActionPerformed

    private void btn_anadirConsAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirConsAlimentoActionPerformed
        if (!tf_cantidad.getText().isEmpty() && !tf_frecuencia.getText().isEmpty()) {

            Ejemplar ej = new Ejemplar(Integer.parseInt(tf_idEjemplar.getText()),
                    new Especie(tf_nomCientificoEjemplar.getText())
            );
            Alimento al = new Alimento(Integer.parseInt(tf_idAlimento.getText()));

            if (fa.anadirConsumirAlimentos(new ConsumirAlimento(ej, al, Integer.parseInt(tf_cantidad.getText()), Integer.parseInt(tf_frecuencia.getText()))) != -1) {
                obterConsumirAlimentos(al.getId());
            }

        }

    }//GEN-LAST:event_btn_anadirConsAlimentoActionPerformed

    private void tf_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cantidadActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anadirConsAlimento;
    private javax.swing.JButton btn_borrarConsAlimento;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_consAlimentos;
    private javax.swing.JTable tabla_ejemplares;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_frecuencia;
    private javax.swing.JTextField tf_idAlimento;
    private javax.swing.JTextField tf_idEjemplar;
    private javax.swing.JTextField tf_nomCientificoEjemplar;
    // End of variables declaration//GEN-END:variables

    private void obterConsumirAlimentos() {
        ModeloTablaConsumirAlimentos mtca;

        mtca = (ModeloTablaConsumirAlimentos) tabla_consAlimentos.getModel();
        mtca.setFilas(fa.obterConsumirAlimentos());
    }
    
    //Solo buscamos os consumidos de un certo alimento
     private void obterConsumirAlimentos(int idAlimento) {
        ModeloTablaConsumirAlimentos mtca;

        mtca = (ModeloTablaConsumirAlimentos) tabla_consAlimentos.getModel();
        mtca.setFilas(fa.obterConsumirAlimentos(idAlimento));
    }

    private void obterEjemplares() {
        ModeloTablaEjemplares mte;

        mte = (ModeloTablaEjemplares) tabla_ejemplares.getModel();
        mte.setFilas(fa.obterEjemplares());
    }

    private void listenerEjemplares() {
        tabla_ejemplares.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
                int fila = tabla_ejemplares.getSelectedRow();
                if (fila != -1) {
                    String idEjemplar = tabla_ejemplares.getValueAt(fila, 0).toString();
                    String nomeCientifico = tabla_ejemplares.getValueAt(fila, 1).toString();
                    tf_idEjemplar.setText(idEjemplar);
                    tf_nomCientificoEjemplar.setText(nomeCientifico);
                }
            }

            @Override
            public void mousePressed(MouseEvent me) {

            }

            @Override
            public void mouseReleased(MouseEvent me) {

            }

            @Override
            public void mouseEntered(MouseEvent me) {

            }

            @Override
            public void mouseExited(MouseEvent me) {

            }

        }
        );

    }
    
    
    private void listenerConsumirAlimentos() {
        tabla_consAlimentos.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
                int fila = tabla_consAlimentos.getSelectedRow();
                if (fila != -1) {
                    String idEjemplar = tabla_consAlimentos.getValueAt(fila, 0).toString();
                    String nomeCientifico = tabla_consAlimentos.getValueAt(fila, 1).toString();
                    String idAlimento = tabla_consAlimentos.getValueAt(fila, 2).toString();
                    String cant = tabla_consAlimentos.getValueAt(fila, 3).toString();
                    String frec = tabla_consAlimentos.getValueAt(fila, 4).toString();
                    
                    tf_idEjemplar.setText(idEjemplar);
                    tf_nomCientificoEjemplar.setText(nomeCientifico);
                    tf_idAlimento.setText(idAlimento);
                    tf_cantidad.setText(cant);
                    tf_frecuencia.setText(frec);
                }
            }

            @Override
            public void mousePressed(MouseEvent me) {

            }

            @Override
            public void mouseReleased(MouseEvent me) {

            }

            @Override
            public void mouseEntered(MouseEvent me) {

            }

            @Override
            public void mouseExited(MouseEvent me) {

            }

        }
        );

    }

}
