/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.Area;
import aplicacion.FachadaAplicacion;
import aplicacion.Taxon;
import java.util.List;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author davidavirn
 */
public class VEspecies extends javax.swing.JDialog {

    /**
     * Creates new form VEspecies
     */
    FachadaAplicacion fa;
    private VPrincipal padre;

    public VEspecies(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        padre=(VPrincipal) parent;
        cargarAreas();
        cargarTaxones();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JTabbedPane();
        panelEspecies = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreCientificoText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NombreComunText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DescripcionText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AreaComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TaxonComboBox = new javax.swing.JComboBox<>();
        AnadirButton = new javax.swing.JButton();
        ActualizarButton = new javax.swing.JButton();
        BorrarButton = new javax.swing.JButton();
        panelEjemplares = new javax.swing.JPanel();
        DiaComboBox = new javax.swing.JComboBox<>();
        MesComboBox = new javax.swing.JComboBox<>();
        AñoComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RevisionesBoton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        buttonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre Científico");

        NombreCientificoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCientificoTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Común");

        NombreComunText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreComunTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripción");

        jLabel4.setText("Área");

        AreaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Taxón");

        AnadirButton.setText("Añadir");

        ActualizarButton.setText("Actualizar");

        BorrarButton.setText("Borrar");

        javax.swing.GroupLayout panelEspeciesLayout = new javax.swing.GroupLayout(panelEspecies);
        panelEspecies.setLayout(panelEspeciesLayout);
        panelEspeciesLayout.setHorizontalGroup(
            panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspeciesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEspeciesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreCientificoText))
                    .addGroup(panelEspeciesLayout.createSequentialGroup()
                        .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreComunText)
                            .addComponent(DescripcionText)
                            .addComponent(AreaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TaxonComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelEspeciesLayout.createSequentialGroup()
                        .addComponent(AnadirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActualizarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BorrarButton)
                        .addGap(0, 277, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEspeciesLayout.setVerticalGroup(
            panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspeciesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreCientificoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreComunText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DescripcionText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AreaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TaxonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnadirButton)
                    .addComponent(ActualizarButton)
                    .addComponent(BorrarButton)))
        );

        panelGeneral.addTab("Especies", panelEspecies);

        DiaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DiaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaComboBoxActionPerformed(evt);
            }
        });

        MesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "910", "11", "12" }));
        MesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("dia");

        jLabel10.setText("mes");

        jLabel11.setText("año");

        RevisionesBoton.setText("Revisiones");

        jLabel12.setText("Fecha nacimiento");

        javax.swing.GroupLayout panelEjemplaresLayout = new javax.swing.GroupLayout(panelEjemplares);
        panelEjemplares.setLayout(panelEjemplaresLayout);
        panelEjemplaresLayout.setHorizontalGroup(
            panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEjemplaresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RevisionesBoton)
                    .addGroup(panelEjemplaresLayout.createSequentialGroup()
                        .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(AñoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        panelEjemplaresLayout.setVerticalGroup(
            panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEjemplaresLayout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jLabel12)
                .addGap(10, 10, 10)
                .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RevisionesBoton)
                .addGap(46, 46, 46))
        );

        panelGeneral.addTab("Ejemplares", panelEjemplares);

        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSalir)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        padre.buscarEspecies();
        this.dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void NombreCientificoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCientificoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCientificoTextActionPerformed

    private void NombreComunTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreComunTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreComunTextActionPerformed

    private void AreaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaComboBoxActionPerformed

    private void DiaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaComboBoxActionPerformed

    private void MesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JButton AnadirButton;
    private javax.swing.JComboBox<String> AreaComboBox;
    private javax.swing.JComboBox<String> AñoComboBox;
    private javax.swing.JButton BorrarButton;
    private javax.swing.JTextField DescripcionText;
    private javax.swing.JComboBox<String> DiaComboBox;
    private javax.swing.JComboBox<Integers> MesComboBox;
    private javax.swing.JTextField NombreCientificoText;
    private javax.swing.JTextField NombreComunText;
    private javax.swing.JButton RevisionesBoton;
    private javax.swing.JComboBox<String> TaxonComboBox;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelEjemplares;
    private javax.swing.JPanel panelEspecies;
    private javax.swing.JTabbedPane panelGeneral;
    // End of variables declaration//GEN-END:variables

    private void cargarAreas() {
        
        List<Area> areas = fa.obtenerAreas(); // obtener la lista de áreas

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();

        for (Area area : areas) {
            modelo.addElement(area.getNombreReserva()); // suponiendo que el área tiene un método getNombre()
        }

        AreaComboBox.setModel(modelo); // asignar el modelo al ComboBox
    }
    
    private void cargarTaxones() {
        List<Taxon> taxones = fa.obtenerTaxones(); // obtener la lista de taxones

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();

        for (Taxon taxon : taxones) {
            modelo.addElement(taxon.getNombre()); // suponiendo que el taxon tiene un método getNombre()
        }

        TaxonComboBox.setModel(modelo); // asignar el modelo al ComboBox
    }

}
