/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.Area;
import aplicacion.Especie;
import aplicacion.FachadaAplicacion;
import aplicacion.Taxon;
import java.util.List;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author davidavirn
 */
public class VEspecies extends javax.swing.JDialog {

    /**
     * Creates new form VEspecies
     */
    FachadaAplicacion fa;
    private VPrincipal padre;
    boolean nuevo=false;
    boolean editar=false;
    private Especie e;

    public VEspecies(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        padre=(VPrincipal) parent;
        cargarTaxones();
        nuevo=true;
        ActualizarButton.setEnabled(false);
        BorrarButton.setEnabled(false);
        

    }
    
    public VEspecies(java.awt.Frame parent, boolean modal, FachadaAplicacion fa, Especie e) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        padre=(VPrincipal) parent;
        NombreCientificoText.setText(e.getNombreCientifico());
        NombreComunText.setText(e.getNombreComun());
        DescripcionText.setText(e.getDescripcion());
        cargarTaxones(e);
        editar=true;
        this.e=e;
        AnadirButton.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JTabbedPane();
        panelEspecies = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreCientificoText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NombreComunText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DescripcionText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TaxonComboBox = new javax.swing.JComboBox<>();
        AnadirButton = new javax.swing.JButton();
        ActualizarButton = new javax.swing.JButton();
        BorrarButton = new javax.swing.JButton();
        panelEjemplares = new javax.swing.JPanel();
        buttonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre Científico");

        NombreCientificoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCientificoTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Común");

        NombreComunText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreComunTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripción");

        jLabel5.setText("Taxón");

        AnadirButton.setText("Añadir");
        AnadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirButtonActionPerformed(evt);
            }
        });

        ActualizarButton.setText("Actualizar");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });

        BorrarButton.setText("Borrar");
        BorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEspeciesLayout = new javax.swing.GroupLayout(panelEspecies);
        panelEspecies.setLayout(panelEspeciesLayout);
        panelEspeciesLayout.setHorizontalGroup(
            panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspeciesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEspeciesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreCientificoText))
                    .addGroup(panelEspeciesLayout.createSequentialGroup()
                        .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreComunText)
                            .addComponent(DescripcionText)
                            .addComponent(TaxonComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelEspeciesLayout.createSequentialGroup()
                        .addComponent(AnadirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActualizarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BorrarButton)
                        .addGap(0, 277, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEspeciesLayout.setVerticalGroup(
            panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspeciesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreCientificoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreComunText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DescripcionText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TaxonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(panelEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnadirButton)
                    .addComponent(ActualizarButton)
                    .addComponent(BorrarButton)))
        );

        panelGeneral.addTab("Especies", panelEspecies);

        javax.swing.GroupLayout panelEjemplaresLayout = new javax.swing.GroupLayout(panelEjemplares);
        panelEjemplares.setLayout(panelEjemplaresLayout);
        panelEjemplaresLayout.setHorizontalGroup(
            panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        panelEjemplaresLayout.setVerticalGroup(
            panelEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        panelGeneral.addTab("Ejemplares", panelEjemplares);

        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSalir)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        padre.buscarEspecies();
        this.dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void NombreCientificoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCientificoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCientificoTextActionPerformed

    private void NombreComunTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreComunTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreComunTextActionPerformed

    private void AnadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirButtonActionPerformed
        Taxon t = new Taxon((String)TaxonComboBox.getSelectedItem(), null, null);
        Especie eNueva = new Especie(
            NombreCientificoText.getText(),
            NombreComunText.getText(),
            DescripcionText.getText(),
            t
        );
        fa.anhadirEspecie(eNueva);
        this.e=eNueva;
    }//GEN-LAST:event_AnadirButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        Taxon t = new Taxon((String)TaxonComboBox.getSelectedItem(), null, null);
        Especie eNueva = new Especie(
            NombreCientificoText.getText(),
            NombreComunText.getText(),
            DescripcionText.getText(),
            t
        );
        fa.actualizarEspecie(e,eNueva);
        this.e=eNueva;
        refreshVentana();
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    private void BorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButtonActionPerformed
        fa.borrarEspecie(e);
    }//GEN-LAST:event_BorrarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JButton AnadirButton;
    private javax.swing.JButton BorrarButton;
    private javax.swing.JTextField DescripcionText;
    private javax.swing.JTextField NombreCientificoText;
    private javax.swing.JTextField NombreComunText;
    private javax.swing.JComboBox<String> TaxonComboBox;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelEjemplares;
    private javax.swing.JPanel panelEspecies;
    private javax.swing.JTabbedPane panelGeneral;
    // End of variables declaration//GEN-END:variables

    
    private void cargarTaxones() {
        List<Taxon> taxones = fa.obtenerTaxones(); // obtener la lista de taxones

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();

        for (Taxon taxon : taxones) {
            modelo.addElement(taxon.getNombre()); // suponiendo que el taxon tiene un método getNombre()
        }

        TaxonComboBox.setModel(modelo); // asignar el modelo al ComboBox
    }

    private void cargarTaxones(Especie e) {
        List<Taxon> taxones = fa.obtenerTaxones(); // obtener la lista de taxones

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();

        for (Taxon taxon : taxones) {
            modelo.addElement(taxon.getNombre()); // suponiendo que el taxon tiene un método getNombre()
        }

        TaxonComboBox.setModel(modelo); // asignar el modelo al ComboBox
        TaxonComboBox.setSelectedItem(e.getTaxon().getNombre());
    }

    private void refreshVentana() {
        NombreCientificoText.setText(e.getNombreCientifico());
        NombreComunText.setText(e.getNombreComun());
        DescripcionText.setText(e.getDescripcion());
        cargarTaxones(e);
    }

}
