/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.Especie;
import aplicacion.Mision;
import aplicacion.Usuario;
import java.awt.Frame;
import java.sql.Date;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author alumnogreibd
 */
public class VMisones extends javax.swing.JDialog {
    aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VMisones2
     */
    public VMisones(java.awt.Frame parent, boolean modal,aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        TablaMisiones.setModel(new ModeloTablaMisiones());
        configurarComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarTextFieldConfig = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        checkBoxTrabajador = new javax.swing.JCheckBox();
        checkBoxEspecie = new javax.swing.JCheckBox();
        checkBoxEstado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMisiones = new javax.swing.JTable();
        btnNueva = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSarlir = new javax.swing.JButton();
        btnCompletada = new javax.swing.JButton();
        btnTrabajadorExperimentado = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Misiones");

        buscarTextFieldConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTextFieldConfigActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        checkBoxTrabajador.setText("Trabajador");
        checkBoxTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxTrabajadorActionPerformed(evt);
            }
        });

        checkBoxEspecie.setText("Especie");

        checkBoxEstado.setText("Estado");

        TablaMisiones.setModel(new ModeloTablaMisiones());
        jScrollPane1.setViewportView(TablaMisiones);

        btnNueva.setText("Nueva Misión");
        btnNueva.setToolTipText("");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnEliminar.setText("Borrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSarlir.setText("Salir");
        btnSarlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSarlirActionPerformed(evt);
            }
        });

        btnCompletada.setText("Completada");
        btnCompletada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletadaActionPerformed(evt);
            }
        });

        btnTrabajadorExperimentado.setText("Escoger Trabajador Más Experimentado");
        btnTrabajadorExperimentado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadorExperimentadoActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarTextFieldConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSarlir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnNueva)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCompletada))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(checkBoxTrabajador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkBoxEspecie)
                                .addGap(18, 18, 18)
                                .addComponent(checkBoxEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                                .addComponent(btnTrabajadorExperimentado)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarTextFieldConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBoxTrabajador)
                            .addComponent(checkBoxEspecie)
                            .addComponent(checkBoxEstado)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTrabajadorExperimentado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNueva)
                    .addComponent(btnEliminar)
                    .addComponent(btnCompletada)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnSarlir)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTextFieldConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTextFieldConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTextFieldConfigActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarMisiones();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void checkBoxTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxTrabajadorActionPerformed

    private void btnSarlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSarlirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSarlirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int selectedRow=TablaMisiones.getSelectedRow();
        
                
                
        if (selectedRow!=-1) {
            ModeloTablaMisiones mm=(ModeloTablaMisiones) TablaMisiones.getModel();
            Mision seleccionado=mm.getFila(selectedRow);
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de que deseas eliminar esta mision?",
            "Confirmar eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {

                fa.eliminarMision(seleccionado);
                mm.setFilas(fa.obtenerMisiones());

                VAviso aviso = new VAviso((Frame)getParent(), true, "Mision eliminada correctamente.");
                aviso.setVisible(true);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Debes seleccionar un trabajador para eliminar.",
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnEliminarActionPerformed
    }
    private void btnCompletadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletadaActionPerformed
        int filaSeleccionada = TablaMisiones.getSelectedRow();

        if (filaSeleccionada != -1) {
            ModeloTablaMisiones modelo = (ModeloTablaMisiones) TablaMisiones.getModel();
            Mision misionSeleccionada = modelo.getMision(filaSeleccionada); // método que devuelve la misión de esa fila

            if (misionSeleccionada.getFechaFin() == null) {
                fa.completarMision(misionSeleccionada);
                JOptionPane.showMessageDialog(this, "Misión marcada como completada.");
            } else {
                JOptionPane.showMessageDialog(this, "La misión ya estaba completada.");
            }

            // Opcional: actualiza la vista si hace falta
            modelo.fireTableRowsUpdated(filaSeleccionada, filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una misión para marcar como completada.");
        }
    }//GEN-LAST:event_btnCompletadaActionPerformed

    private void btnTrabajadorExperimentadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadorExperimentadoActionPerformed
        // TODO add your handling code here:
        String especie = buscarTextFieldConfig.getText().trim(); 
        if (!especie.isEmpty()) {
            Usuario trabajador = fa.obtenerTrabajadorMasExperimentado(especie); // pasar la especie
            if (trabajador != null && checkBoxEspecie.isSelected()) {
                VAviso aviso = new VAviso((Frame) getParent(), true, "El trabajador más experimentado para la especie '" + especie + "' es: " + trabajador);
                aviso.setVisible(true);
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(VMisones.this, 
                    "No se pudo determinar el trabajador más experimentado para la especie '" + especie + "'.",
                    "Aviso", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(VMisones.this, 
                "Por favor, introduzca una especie.",
                "Campo vacío", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    
    
    }//GEN-LAST:event_btnTrabajadorExperimentadoActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        // TODO add your handling code here:
        Usuario usuarioMision= fa.obtenerTrabajadorMision();
        Mision nuevaMision = new Mision(
            usuarioMision,
            "", // especie
            Date.valueOf(LocalDate.now()), // fechaInicio: hoy
            null, // fechaFin: no completada
            "" // descripción
        );
    // Obtener el modelo de la tabla
     ModeloTablaMisiones mm = ( ModeloTablaMisiones) TablaMisiones.getModel();

    mm.anhadeFila(nuevaMision);

    int lastRow = mm.getRowCount() - 1;
    TablaMisiones.setRowSelectionInterval(lastRow, lastRow);

    TablaMisiones.editCellAt(lastRow, 0);

   
    TablaMisiones.requestFocusInWindow();
    TablaMisiones.requestFocusInWindow();
        
       
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    // Obtener el modelo de la tabla
    ModeloTablaMisiones modelo = (ModeloTablaMisiones) TablaMisiones.getModel();

    // Recoger las misiones actuales y las originales
    List<Mision> misionesActuales = modelo.getMisiones();
    List<Mision> misionesOriginales = modelo.getMisionesOriginales(); // Obtienes las misiones originales




    for (int i = 0; i < misionesActuales.size(); i++) {
        Mision misionActual = misionesActuales.get(i);
        Mision misionOriginal = (i < misionesOriginales.size()) ? misionesOriginales.get(i) : null;



        // Si la misión original existe, compararla con la misión actual
        if (misionOriginal != null) {
            // Verificar si los campos clave han cambiado
            if (hasMisionChanged(misionOriginal, misionActual)) {
                // Si ha cambiado, actualizarla
                fa.actualizarMision(misionActual, misionOriginal);
            }
        } else {
            // Si la misión original es null, significa que es una misión nueva, así que la agregamos
            fa.agregarNuevaMision(misionActual);
        }
    }

    // Mostrar mensaje de éxito
    JOptionPane.showMessageDialog(this, "Misiones actualizadas correctamente.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private boolean hasMisionChanged(Mision misionOriginal, Mision misionActual) {
        boolean nombresDistintos = !misionOriginal.getTrabajador().getNombre().equals(misionActual.getTrabajador().getNombre());
        boolean especieDistinta = !misionOriginal.getEspecie().equals(misionActual.getEspecie());
        boolean descripcionDistinta = !misionOriginal.getDescripcion().equals(misionActual.getDescripcion());
        boolean fechaInicioDistinta = !misionOriginal.getFechaInicio().equals(misionActual.getFechaInicio());

        boolean fechaFinDistinta = false;
        if (misionOriginal.getFechaFin() == null && misionActual.getFechaFin() != null) {
            fechaFinDistinta = true;
        } else if (misionOriginal.getFechaFin() != null && !misionOriginal.getFechaFin().equals(misionActual.getFechaFin())) {
            fechaFinDistinta = true;
        }

        return nombresDistintos || especieDistinta || descripcionDistinta || fechaInicioDistinta || fechaFinDistinta;
    }

    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMisiones;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCompletada;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton btnSarlir;
    private javax.swing.JButton btnTrabajadorExperimentado;
    private javax.swing.JTextField buscarTextFieldConfig;
    private javax.swing.JCheckBox checkBoxEspecie;
    private javax.swing.JCheckBox checkBoxEstado;
    private javax.swing.JCheckBox checkBoxTrabajador;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void buscarMisiones() {
        ModeloTablaMisiones mm;
        mm=(ModeloTablaMisiones) TablaMisiones.getModel();
        String textoBusqueda=buscarTextFieldConfig.getText().trim();
         if (textoBusqueda.isEmpty()) {
        
        mm.setFilas(fa.obtenerMisiones());
       }
       else if (checkBoxTrabajador.isSelected()) {
           mm.setFilas(fa.obtenerMisionesTrabajador(textoBusqueda));
           

       }else if (checkBoxEstado.isSelected()) {
           mm.setFilas(fa.obtenerMisonesEstado(textoBusqueda));
           

       }else if (checkBoxEspecie.isSelected()) {
           mm.setFilas(fa.obtenerMisionesEspecie(textoBusqueda));
           

       }else{
           VAviso va= new VAviso((Frame)getParent(), true, "Selecciona un criterio de búsqueda");
           va.setVisible(true);

       }
    }
    public void configurarComboBoxes(){
        
            // Suponiendo que ya tienes la lista de trabajadores y especies
    List<Usuario> listaTrabajadores = fa.obtenerTodosLosTrabajadores(); // Obtener trabajadores
    List<Especie> listaEspecies = fa.obtenerEspecies("");

    // Crear los combo boxes
    JComboBox<String> comboTrabajadores = new JComboBox<>();
    for (Usuario u : listaTrabajadores) {
        comboTrabajadores.addItem(u.getNombre());
    }

    JComboBox<String> comboEspecies = new JComboBox<>();
    for (Especie especie : listaEspecies) {
        comboEspecies.addItem(especie.getNombreCientifico());
    }

    // Asignar el editor del combo box a las columnas correspondientes
    TablaMisiones.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(comboTrabajadores));
    TablaMisiones.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(comboEspecies));

    }
}
