/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;

import aplicacion.Especie;
import aplicacion.FachadaAplicacion;


/**
 *
 * @author basesdatos
 */
public class VPrincipal extends javax.swing.JFrame {
  
    FachadaAplicacion fa;
    
    /** Creates new form VPrincipal */
    public VPrincipal(FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEspecies = new javax.swing.JTable();
        jButtonNuevo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        menuItemTrabajadores = new javax.swing.JMenuItem();
        menuItemMisiones = new javax.swing.JMenuItem();
        menuItemAreaGeo = new javax.swing.JMenuItem();
        menuItemAlimentos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservas Naturales");
        setName("vPrincipal"); // NOI18N
        setResizable(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre Científico");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        tablaEspecies.setModel(new ModeloTablaEspecies());
        jScrollPane1.setViewportView(tablaEspecies);

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        menuPrincipal.setLabel("Administración");

        menuItemTrabajadores.setText("Trabajadores");
        menuItemTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTrabajadoresActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuItemTrabajadores);

        menuItemMisiones.setText("Misiones");
        menuItemMisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMisionesActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuItemMisiones);

        menuItemAreaGeo.setText("Áreas Geográficas");
        menuItemAreaGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAreaGeoActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuItemAreaGeo);

        menuItemAlimentos.setLabel("Alimentos");
        menuItemAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlimentosActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuItemAlimentos);

        jMenuItem1.setText("Revisiones (todas)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuPrincipal.add(jMenuItem1);

        jMenuItem2.setText("Clinicas (sin revisiones)");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuPrincipal.add(jMenuItem2);

        jMenuBar1.add(menuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuItemAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlimentosActionPerformed
        VAlimentos va = new VAlimentos(this, true, fa);
        va.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAlimentosActionPerformed

    private void menuItemTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTrabajadoresActionPerformed
        // TODO add your handling code here:
        VTrabajadores vt=new VTrabajadores(this, true, fa);
        vt.setVisible(true);
    }//GEN-LAST:event_menuItemTrabajadoresActionPerformed

    private void menuItemMisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMisionesActionPerformed
        // TODO add your handling code here:
        VMisones vm=new VMisones(this, true,fa);
        vm.setVisible(true);
    }//GEN-LAST:event_menuItemMisionesActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarEspecies();
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        fa.nuevaEspecie();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        ModeloTablaEspecies mte = (ModeloTablaEspecies) tablaEspecies.getModel();
        Especie e = mte.obtenerEspecie(tablaEspecies.getSelectedRow());
        fa.editarEspecie(e);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void menuItemAreaGeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAreaGeoActionPerformed
        // TODO add your handling code here:
        VAreasGeograficas vag = new VAreasGeograficas(this, true, fa);
        vag.setVisible(true);
    }//GEN-LAST:event_menuItemAreaGeoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       VRevisiones vr = new VRevisiones(this,true,fa);
       vr.setVisible(true); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VClinicas vc = new VClinicas(this,true,fa);
        vc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JMenuItem menuItemAlimentos;
    private javax.swing.JMenuItem menuItemAreaGeo;
    private javax.swing.JMenuItem menuItemMisiones;
    private javax.swing.JMenuItem menuItemTrabajadores;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JTable tablaEspecies;
    // End of variables declaration//GEN-END:variables

    public void buscarEspecies() {
        ModeloTablaEspecies m;

        m = (ModeloTablaEspecies) tablaEspecies.getModel();
        m.setFilas(fa.obtenerEspecies(jTextFieldNombre.getText()));

        if (m.getRowCount() > 0) {
            tablaEspecies.setRowSelectionInterval(0, 0);
            jButtonEditar.setEnabled(true);
        } else {
            jButtonEditar.setEnabled(false);
        }


    }

   
}
