/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;

import aplicacion.FachadaAplicacion;


/**
 *
 * @author basesdatos
 */
public class VPrincipal extends javax.swing.JFrame {
  
    FachadaAplicacion fa;
    
    /** Creates new form VPrincipal */
    public VPrincipal(FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        menuItemTrabajadores = new javax.swing.JMenuItem();
        menuItemMisiones = new javax.swing.JMenuItem();
        menuItemAreaGeo = new javax.swing.JMenuItem();
        menuItemAlimentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservas Naturales");
        setName("vPrincipal"); // NOI18N
        setResizable(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("NESTA VENTANA PTRINCIPAL METEREMOS O DE ESPECIAS E TAL COMO SE FOSE O DA BIBLIOTECA COS LIBROS");

        jLabel2.setText("DESPOIS DENTRO ESTARÁN OS TAXÓNS DO CARALLO, REVISIÓNS DOS ANIMALES. ALIMENTOS ETC...");

        menuPrincipal.setLabel("Administración");

        menuItemTrabajadores.setText("Trabajadores");
        menuItemTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTrabajadoresActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuItemTrabajadores);

        menuItemMisiones.setText("Misiones");
        menuItemMisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMisionesActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuItemMisiones);

        menuItemAreaGeo.setText("Áreas Geográficas");
        menuPrincipal.add(menuItemAreaGeo);

        menuItemAlimentos.setLabel("Alimentos");
        menuItemAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlimentosActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuItemAlimentos);

        jMenuBar1.add(menuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(246, 246, 246)
                .addComponent(btnSalir)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuItemAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAlimentosActionPerformed

    private void menuItemTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTrabajadoresActionPerformed
        // TODO add your handling code here:
        VTrabajadores vt=new VTrabajadores(this, true, fa);
        vt.setVisible(true);
    }//GEN-LAST:event_menuItemTrabajadoresActionPerformed

    private void menuItemMisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMisionesActionPerformed
        // TODO add your handling code here:
        VMisones vm=new VMisones(this, true,fa);
        vm.setVisible(true);
    }//GEN-LAST:event_menuItemMisionesActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemAlimentos;
    private javax.swing.JMenuItem menuItemAreaGeo;
    private javax.swing.JMenuItem menuItemMisiones;
    private javax.swing.JMenuItem menuItemTrabajadores;
    private javax.swing.JMenu menuPrincipal;
    // End of variables declaration//GEN-END:variables

   
}
