/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.Ejemplar;
import aplicacion.ClinicaMedica;
import aplicacion.Revision;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
/**
 *
 * @author alumnogreibd
 */
public class VRevisiones extends javax.swing.JDialog {
        aplicacion.FachadaAplicacion fa;
        Ejemplar ejemplarRevision;
        ClinicaMedica clinicaRevision;
        
        
    /**
     * Creates new form VRevisiones
     */
    public VRevisiones(java.awt.Frame parent, boolean modal, 
            aplicacion.FachadaAplicacion fa,Ejemplar ejemplar,ClinicaMedica clinica) {
        super(parent, modal);
        this.fa=fa;
        this.clinicaRevision= clinica;
        this.ejemplarRevision = ejemplar;
       
        initComponents();
        
        TablaRevisiones.setModel(new ModeloTablaRevisiones());
        ModeloTablaRevisiones mt;
        mt=(ModeloTablaRevisiones)TablaRevisiones.getModel();
        String nClinica = this.clinicaRevision.getNombre();
        int Id = this.ejemplarRevision.getId();
        System.out.println(this.ejemplarRevision.getId());  // imprime y añade salto de línea
       
        mt.setFilas(fa.obtenerRevisiones(nClinica,Id));
        listenerSeleccionRevision();
        
    }

    /**
     * ModeloTablaRevisiones mt;
    TablaRevisiones
    mt=(ModeloTablaRevisiones) TablaRevisiones.get
 
    String textoBusqueda=TextFileBuscarTrabajadores.getText().trim();
    nombreCheck.setVisible(true);
    dniCheck.setVisible(true);
    if (textoBusqueda.isEmpty()) {
        
     mt.setFilas(fa.obtenerTodosLosTrabajadores());
    }
    else if (dniCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresDni(textoBusqueda));
        nombreCheck.setVisible(false);
        
    }else if (nombreCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresNombre(textoBusqueda));
        dniCheck.setVisible(false);
        
    }else{
        VAviso va= new VAviso((Frame)getParent(), true, "Selecciona un criterio de búsqueda");
        va.setVisible(true);
        
    }

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRevisiones = new javax.swing.JTable();
        InformeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AñadirBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaRevisiones.setModel(new ModeloTablaRevisiones());
        jScrollPane1.setViewportView(TablaRevisiones);

        InformeField.setPreferredSize(new java.awt.Dimension(1000, 30));

        jLabel1.setText("informe");

        AñadirBoton.setText("AÑADIR");
        AñadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(InformeField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 94, Short.MAX_VALUE)
                                .addComponent(AñadirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(salirBoton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InformeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AñadirBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(salirBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirBotonActionPerformed
        // TODO add your handling code here:
        
        fa.añadirRevsion(this.clinicaRevision,this.ejemplarRevision,this.InformeField.getText());
        this.dispose();
    }//GEN-LAST:event_AñadirBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirBoton;
    private javax.swing.JTextField InformeField;
    private javax.swing.JTable TablaRevisiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salirBoton;
    // End of variables declaration//GEN-END:variables

    
    private void listenerSeleccionRevision() {
        TablaRevisiones.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
                int fila = TablaRevisiones.getSelectedRow();
                if (fila != -1) {
                    ModeloTablaRevisiones mt;
                    mt=(ModeloTablaRevisiones)TablaRevisiones.getModel();
                    Revision revi = mt.getFila(fila);
                    InformeField.setText(revi.getInforme());
                    
                    
                   
                }
                          
                
            }

            @Override
            public void mousePressed(MouseEvent me) {
               
            }

            @Override
            public void mouseReleased(MouseEvent me) {
               
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                
            }

            @Override
            public void mouseExited(MouseEvent me) {
               
            }

   
        }
        );
    }


}

