/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Usuario;
import java.awt.Frame;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author alumnogreibd
 */
public class VTrabajadores extends javax.swing.JDialog {
    aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VTrabajadores
     */
    public VTrabajadores(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        tabla_traballadores.setModel(new ModeloTablaTrabajadores());
        asignarModeloSpinner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFileBuscarTrabajadores = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        dniCheck = new javax.swing.JCheckBox();
        nombreCheck = new javax.swing.JCheckBox();
        sp_traballadores = new javax.swing.JScrollPane();
        tabla_traballadores = new javax.swing.JTable();
        bntNuevo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        bntMoverArea = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnReducirJornada = new javax.swing.JButton();
        spinner_porcentaxeReducir = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trabajadores");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        TextFileBuscarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFileBuscarTrabajadoresActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        dniCheck.setSelected(true);
        dniCheck.setText("dni");

        nombreCheck.setText("Nombre");

        tabla_traballadores.setModel(new ModeloTablaTrabajadores());
        tabla_traballadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_traballadoresMouseClicked(evt);
            }
        });
        sp_traballadores.setViewportView(tabla_traballadores);

        bntNuevo.setText("Nuevo");
        bntNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNuevoActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        bntMoverArea.setText("Mover Área");
        bntMoverArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMoverAreaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnReducirJornada.setText("Reducir jornada de área más poblada");
        btnReducirJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReducirJornadaActionPerformed(evt);
            }
        });

        spinner_porcentaxeReducir.setToolTipText("");

        jLabel1.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntMoverArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dniCheck)
                                        .addGap(52, 52, 52)
                                        .addComponent(nombreCheck)
                                        .addGap(0, 146, Short.MAX_VALUE))
                                    .addComponent(TextFileBuscarTrabajadores))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sp_traballadores, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReducirJornada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel1))
                                    .addComponent(spinner_porcentaxeReducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextFileBuscarTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniCheck)
                    .addComponent(nombreCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addComponent(sp_traballadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReducirJornada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinner_porcentaxeReducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntNuevo)
                    .addComponent(btnActualizar)
                    .addComponent(bntMoverArea)
                    .addComponent(btnSalir)
                    .addComponent(btnEliminar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarUsuarios();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tabla_traballadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_traballadoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_traballadoresMouseClicked

    private void bntNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                         

        Usuario novoUsr = new Usuario("", "", 0.0f, 0, null);

        ModeloTablaTrabajadores mtt = (ModeloTablaTrabajadores) tabla_traballadores.getModel();

        mtt.anhadeFila(novoUsr);

        int ultFila = mtt.getRowCount() - 1;
        tabla_traballadores.setRowSelectionInterval(ultFila, ultFila);
        tabla_traballadores.editCellAt(ultFila, 0);
        tabla_traballadores.requestFocusInWindow();
        mtt.setCrearTrabajador(true);
    }

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        ModeloTablaTrabajadores mt = (ModeloTablaTrabajadores) tabla_traballadores.getModel();

        
        List<Usuario> trabajadores = mt.getFilas();

        
        if (mt.isCrearTrabajador()) {
            
            String dni = (String) mt.getValueAt(mt.getRowCount() - 1, 0);
            String nombre = (String) mt.getValueAt(mt.getRowCount() - 1, 1);
            int horas = (Integer) mt.getValueAt(mt.getRowCount() - 1, 2); 
            float sueldo = (Float) mt.getValueAt(mt.getRowCount() - 1, 3); 
            String nombre_reserva = (String) mt.getValueAt(mt.getRowCount() - 1, 4);

            
            fa.nuevoTrabajador(dni, nombre, horas, sueldo,nombre_reserva);

            
            mt.setCrearTrabajador(false);
        }

        
        for (Usuario t : trabajadores) {
            fa.actualizarTrabajador(t); 
        }

        mt.fireTableDataChanged();
        
        VAviso aviso = new VAviso((Frame) getParent(), true, "Cambios guardados correctamente.");
        aviso.setVisible(true);
        JOptionPane.showMessageDialog(this, "Cambios guardados correctamente.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void bntMoverAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMoverAreaActionPerformed
        int fila = tabla_traballadores.getSelectedRow();

        if (fila != -1) {
            ModeloTablaTrabajadores mt = (ModeloTablaTrabajadores) tabla_traballadores.getModel();
            Usuario seleccionado = mt.getFila(fila);

            VMoverArea vMA = new VMoverArea((Frame) getParent(), true, fa, seleccionado);
            vMA.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debes seleccionar un trabajador para mover de área.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bntMoverAreaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila =tabla_traballadores.getSelectedRow();
        
                
                
        if (fila!=-1) {
            ModeloTablaTrabajadores mtt =(ModeloTablaTrabajadores) tabla_traballadores.getModel();
            Usuario seleccionado= mtt.getFila(fila);
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de que deseas eliminar al trabajador con DNI: " + seleccionado.getDni() + "?",
            "Confirmar eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {

                fa.eliminarTrabajador(seleccionado.getDni());
                mtt.setFilas(fa.obtenerTodosLosTrabajadores());

                VAviso aviso = new VAviso((Frame)getParent(), true, "Trabajador eliminado correctamente.");
                aviso.setVisible(true);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Debes seleccionar un trabajador para eliminar.",
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);

            }   
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TextFileBuscarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFileBuscarTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFileBuscarTrabajadoresActionPerformed

    private void btnReducirJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReducirJornadaActionPerformed
        int res = fa.reducirXornadaAreaMaisSaturada((int) spinner_porcentaxeReducir.getValue());
        
        if (res != -1) {
            buscarUsuarios();
        } else {

        }
    }//GEN-LAST:event_btnReducirJornadaActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFileBuscarTrabajadores;
    private javax.swing.JButton bntMoverArea;
    private javax.swing.JButton bntNuevo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnReducirJornada;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox dniCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox nombreCheck;
    private javax.swing.JScrollPane sp_traballadores;
    private javax.swing.JSpinner spinner_porcentaxeReducir;
    private javax.swing.JTable tabla_traballadores;
    // End of variables declaration//GEN-END:variables

private void buscarUsuarios(){
    ModeloTablaTrabajadores mt;
    mt=(ModeloTablaTrabajadores) tabla_traballadores.getModel();
 
    String textoBusqueda=TextFileBuscarTrabajadores.getText().trim();
    
    if (textoBusqueda.isEmpty()) {
        
     mt.setFilas(fa.obtenerTodosLosTrabajadores());
    }
    else if (dniCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresDni(textoBusqueda));
        
    }else if (nombreCheck.isSelected()) {
        mt.setFilas(fa.obtenerTrabajadoresNombre(textoBusqueda)); 
    }else{
        VAviso va= new VAviso((Frame)getParent(), true, "Selecciona un criterio de búsqueda");
        va.setVisible(true);
        
    }
}

private void asignarModeloSpinner() {
    SpinnerNumberModel modelo = new SpinnerNumberModel(0, 0, 100, 1);
    spinner_porcentaxeReducir.setModel(modelo);
}



}
